version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: US/Eastern
  open-pull-requests-limit: 2
  reviewers:
  - klgh
  assignees:
  - klgh
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: ini
    versions:
    - 1.3.7
    - 1.3.8
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.8.0
  - dependency-name: gatsby
    versions:
    - 2.29.3
