# These rules will change if you change your site’s custom domains or HTTPS settings

# Redirect default Netlify subdomain to primary domain
https://ecstatic-banach-93bdc7.netlify.com/* https://kaleighscruggs.com/:splat 301!
